# Generated by Django 2.1.5 on 2020-08-02 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('explanation', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BoardPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=10)),
                ('document', models.TextField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentComments', models.TextField(max_length=500)),
                ('writer', models.CharField(max_length=10)),
                ('document', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('boardPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardsapi.BoardPosts')),
            ],
        ),
        migrations.CreateModel(
            name='likeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('tendency', models.CharField(choices=[('like', '좋아요'), ('dislike', '싫어요')], default='좋아요/싫어요', max_length=5, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardsapi.Comment')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardsapi.BoardPosts')),
            ],
        ),
    ]
