# Generated by Django 2.1.5 on 2020-08-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardposts',
            name='boardtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Board', to='boardsapi.Board'),
        ),
    ]
