FROM centos:7.8

ENV PYTHONUNBUFFERED 0

RUN yum update -y && yum install -y python3-pip python3

WORKDIR /app

ADD    nginx.repo          /etc/yum.repos.d/
ADD    appdev.service      /etc/systemd/system/
ADD    django-test         /etc/nginx/sites-available/
ADD    requirements.txt    /app/
RUN    pip3 install -r requirements.txt
RUN    pip3 install Django==2.1.5
RUN    pip3 install djangorestframework