version: '3'

volumes:
  django_sample_db_dev: {}

services:
  app:
    image: centos/7
    privileged : true

  django:
    build:
      context: .
      dockerfile: ./Dockerfile-DEV
    environment:
      - DJANGO_DEBUG=True
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        pip3 install gunicorn
        systemctl enable appdev
        systemctl start appdev
        yum repolist ; yum clean all
        yum install -y nginx
        ln -s /etc/nginx/sites-available/django-test /etc/nginx/sites-enabled
        systemctl enable nginx
        systemctl start nginx
       
    restart: always
    volumes:
      - ./:/app/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro