version: '3'

volumes:
  django_sample_db_dev: {}

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - django_sample_db_dev:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=sampledb
  #     - POSTGRES_USER=sampleuser
  #     - POSTGRES_PASSWORD=samplesecret
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  django:
    build:
      context: .
      dockerfile: ./Dockerfile-DEV
    environment:
      - DJANGO_DEBUG=True
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate
        nohup python3 manage.py runserver 0:8000 &
        echo -e '\r'
    restart: always
    volumes:
      - ./:/app/