# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "push"
  - "test"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "dhdiagram4011/reservation-app-project"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"
  
  build:
    title: "Building Docker image"
    type: "build"
    image_name: "dhdiagram/apiapp"
    working_directory: "${{clone}}"
    tag: "golden"
    dockerfile: "Dockerfile"
    stage: "build"
    
  build_my_app:
          type: build
          working_directory: "${{clone}}"
          image-name: dhdiagram/apiapp
          tag: golden
  
  push_to_my_registry:
        stage: 'push'
        type: push
        title: Pushing to a registry
        candidate: ${{build_my_app}}
        tag: 'golden'
        registry: dockerhub
        
  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "dhdiagram/apiapp:develop_20200906" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "nohup python3 ${{clone}}/manage.py runserver 0:8000 &"
    stage: "test"
  
  deploy to ecs:
    type: ecs-deploy
    arguments:
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      aws-region: ap-northeast-2
      cluster_name: reservation-apiapp-2
      service_name: reservation-apiapp-svc-2
      image: dhdiagram/apiapp:golden
    
