# Generated by Django 2.1.5 on 2020-08-25 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flightAircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_name', models.CharField(max_length=10)),
                ('aircraft_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='flightNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='flightSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=10, null=True)),
                ('arrival', models.CharField(max_length=10, null=True)),
                ('flight_time', models.DateTimeField()),
                ('daytogo', models.DateField()),
                ('comingDay', models.DateField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 8, 25, 12, 36, 57, 727496, tzinfo=utc))),
                ('FlightAircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_api.flightAircraft')),
                ('FlightNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_api.flightNumber')),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_season_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('low_season_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='seatClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='flightsection',
            name='Price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_api.price'),
        ),
        migrations.AddField(
            model_name='flightsection',
            name='SeatClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_api.seatClass'),
        ),
    ]
