version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 reservation-app-project/manage.py runserver 0:8000
          name: reservation-ticket-app-test-build

workflows:
  main:
    jobs:
      - build-and-test
