# Generated by Django 3.1.5 on 2021-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=4)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_birth', models.DateField(auto_now_add=True)),
                ('stamp_number', models.IntegerField(max_length=2)),
                ('customer_create', models.DateTimeField()),
            ],
        ),
    ]
