# Generated by Django 2.2.1 on 2020-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(help_text='이메일 주소를 입력해 주세요', max_length=200),
        ),
    ]
