# Generated by Django 2.2.1 on 2020-06-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200601_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(help_text='이메일 주소를 입력해 주세요', max_length=200),
        ),
    ]
