# Generated by Django 2.2.1 on 2020-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200601_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(help_text='패스워드를 입력해 주세요', max_length=200),
        ),
    ]
