# Generated by Django 2.2.1 on 2020-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200601_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
