# Generated by Django 2.2.1 on 2020-06-02 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailticket',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 12, 32, 59, 893869, tzinfo=utc)),
        ),
    ]
