# Generated by Django 2.2.1 on 2020-06-01 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 11, 7, 5, 5822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 11, 7, 5, 4657, tzinfo=utc)),
        ),
    ]
