# Generated by Django 2.2.1 on 2020-06-03 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200602_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailticket',
            name='FlightAircraft',
        ),
        migrations.RemoveField(
            model_name='emailticket',
            name='FlightNumber',
        ),
        migrations.RemoveField(
            model_name='emailticket',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='emailticket',
            name='SeatClass',
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 12, 53, 34, 348635, tzinfo=utc)),
        ),
    ]
