# Generated by Django 2.1.5 on 2020-07-07 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200707_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailticket',
            name='Price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.price'),
        ),
        migrations.AlterField(
            model_name='emailticket',
            name='SeatClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.seatClass'),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 12, 9, 51, 912849, tzinfo=utc)),
        ),
    ]
