# Generated by Django 2.2.1 on 2020-06-01 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20200601_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 12, 25, 22, 113740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 12, 25, 22, 112574, tzinfo=utc)),
        ),
    ]
