# Generated by Django 2.2.1 on 2020-06-03 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20200603_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 13, 16, 55, 33759, tzinfo=utc)),
        ),
    ]
