# Generated by Django 2.2.1 on 2020-06-04 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20200604_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 11, 15, 9, 294498, tzinfo=utc)),
        ),
    ]
