# Generated by Django 2.2.1 on 2020-06-17 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20200617_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailticket',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 13, 38, 37, 610438, tzinfo=utc)),
        ),
    ]
