# Generated by Django 2.2.1 on 2020-06-17 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20200617_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailticket',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 13, 43, 38, 786833, tzinfo=utc)),
        ),
    ]
