# Generated by Django 3.1.3 on 2020-11-22 03:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0026_auto_20200911_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 3, 59, 44, 149180, tzinfo=utc)),
        ),
    ]
