# Generated by Django 2.1.5 on 2020-12-10 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0028_auto_20201122_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 11, 21, 53, 516529, tzinfo=utc)),
        ),
    ]
