# Generated by Django 2.1.5 on 2020-12-15 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0030_auto_20201215_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 9, 48, 49, 502644, tzinfo=utc)),
        ),
    ]
