# Generated by Django 2.1.5 on 2021-01-03 03:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0031_auto_20201215_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 3, 49, 56, 105762, tzinfo=utc)),
        ),
    ]
