# Generated by Django 2.1.5 on 2021-01-03 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0032_auto_20210103_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 4, 18, 10, 732779, tzinfo=utc)),
        ),
    ]
