# Generated by Django 2.1.5 on 2021-01-03 04:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0033_auto_20210103_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 4, 25, 25, 766719, tzinfo=utc)),
        ),
    ]
