# Generated by Django 2.1.5 on 2021-01-07 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0034_auto_20210103_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 11, 2, 34, 317175, tzinfo=utc)),
        ),
    ]
