# Generated by Django 3.1.5 on 2021-01-09 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0035_auto_20210107_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 8, 32, 40, 579343, tzinfo=utc)),
        ),
    ]
