# Generated by Django 3.1.5 on 2021-01-09 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0038_auto_20210109_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 8, 46, 51, 555732, tzinfo=utc)),
        ),
    ]
