# Generated by Django 3.1.5 on 2021-01-09 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0040_auto_20210109_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 8, 50, 29, 670963, tzinfo=utc)),
        ),
    ]
