# Generated by Django 2.1.5 on 2021-01-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=10)),
                ('MG_number', models.CharField(max_length=3)),
                ('Store_name', models.CharField(max_length=100)),
                ('Store_phone', models.CharField(max_length=20)),
                ('Store_address_01', models.CharField(max_length=100)),
                ('Store_address_02', models.CharField(max_length=100)),
                ('Representative', models.CharField(max_length=4)),
                ('store_number', models.CharField(max_length=5)),
                ('bln', models.CharField(max_length=20)),
                ('stamp_design', models.ImageField(upload_to='')),
            ],
        ),
    ]
